const initProjects = [
  {
    taskName: "InuisToDoの使い方",
    taskId: "d0046772-31c3-481d-a665-ae5280dae73a",
    isClose: false,
    isSelected: false,
    isHidden: false,
    checked: false,
    childTasks: [
      {
        taskName: "メインビュー操作",
        taskId: "c4f041c7-cefc-4316-8698-d9d8754e939c",
        isClose: false,
        isSelected: false,
        isFocus: true,
        checked: false,
        childTasks: [
          {
            taskName: "プロジェクトの開始",
            taskId: "4311e973-8c51-464a-8314-259eb3a35bc0",
            isClose: false,
            isSelected: false,
            isFocus: true,
            checked: false,
            childTasks: [
              {
                taskName: "右上のプラスボタン",
                taskId: "3d1d38e3-d64c-4e3c-a3a0-7739ebe34b08",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [],
              },
            ],
          },
          {
            taskName: "タスク等の削除",
            taskId: "db259a5f-7136-41da-94c9-5af82ce6a2db",
            isClose: false,
            isSelected: false,
            isFocus: true,
            checked: false,
            childTasks: [
              {
                taskName: "ゴミ箱マーク",
                taskId: "2e065529-79d1-449e-a2ac-c30a5617cf4d",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [],
              },
              {
                taskName: "削除サンプル１",
                taskId: "08b7a002-3bc4-4b6d-afab-eea1ca57e668",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [],
              },
              {
                taskName: "削除サンプル２",
                taskId: "0acacdf8-1acc-43cc-9542-f6015ba27f02",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [],
              },
            ],
          },
          {
            taskName: "タスク追加",
            taskId: "a8bd0504-c8b9-4500-8416-925601b3af49",
            isClose: false,
            isSelected: false,
            isFocus: true,
            checked: false,
            childTasks: [
              {
                taskName: "タスク右横プラスマーク",
                taskId: "c8463630-5db5-464b-b6e4-318eab464f5d",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [],
              },
              {
                taskName: "フラグの下に見えないプラスマーク",
                taskId: "50d7831a-d7ff-4275-b71f-743b47ade44b",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [],
              },
            ],
          },
          {
            taskName: "タスクの並び替え",
            taskId: "b453b1d4-3675-444a-ad8e-debebce9ed31",
            isClose: false,
            isSelected: false,
            isFocus: true,
            checked: false,
            childTasks: [
              {
                taskName: "タスクを長押し",
                taskId: "f657f9a2-e0b9-40c9-bb6e-20f33298d8b7",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [
                  {
                    taskName: "上下ドラッグ→リスト内の移動",
                    taskId: "9e9b1f13-6e8b-4a0b-8e22-db605040ff2c",
                    isClose: false,
                    isSelected: false,
                    isFocus: true,
                    checked: false,
                    childTasks: [],
                  },
                  {
                    taskName: "左右ドラッグ（適度）＆ドロップ→階層を一つ移動",
                    taskId: "0398dbcf-3e85-4e8a-a0bf-b0607b104051",
                    isClose: false,
                    isSelected: false,
                    isFocus: true,
                    checked: false,
                    childTasks: [],
                  },
                ],
              },
            ],
          },
          {
            taskName: "サブタスクの表示/非表示",
            taskId: "60bd1526-5ec5-49a9-85f1-c12950430c26",
            isClose: false,
            isSelected: false,
            isFocus: true,
            checked: false,
            childTasks: [
              {
                taskName: "左下トグルボタン∨",
                taskId: "d5e0d675-f1a0-4500-a6ce-00b69a28d966",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [
                  {
                    taskName: "サンプルアイテム１",
                    taskId: "16113d91-7f23-454a-9e36-a86d09ca83ff",
                    isClose: false,
                    isSelected: false,
                    isFocus: true,
                    checked: false,
                    childTasks: [],
                  },
                  {
                    taskName: "サンプルアイテム２",
                    taskId: "c8e679b1-fe31-4ee1-a99c-9608f738afab",
                    isClose: false,
                    isSelected: false,
                    isFocus: true,
                    checked: false,
                    childTasks: [],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        taskName: "サイドバー操作",
        taskId: "d52e999f-30c8-4f84-b0a7-7b605b6b20e5",
        isClose: false,
        isSelected: false,
        isFocus: true,
        checked: false,
        childTasks: [
          {
            taskName: "削除",
            taskId: "0e3174c2-81b4-40c3-8db1-834e72fc60b5",
            isClose: false,
            isSelected: false,
            isFocus: true,
            checked: false,
            childTasks: [
              {
                taskName: "ゴミ箱ボタン",
                taskId: "a2757cce-861c-44d6-ba0c-132ea0dfd228",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [],
              },
            ],
          },
          {
            taskName: "プロジェクトの表示/非表示",
            taskId: "a0881126-df27-43cd-96b0-55f26299040b",
            isClose: false,
            isSelected: false,
            isFocus: true,
            checked: false,
            childTasks: [
              {
                taskName: "目玉ボタン",
                taskId: "5eafd8b6-207e-4639-a91f-c84654ca5232",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [],
              },
            ],
          },
          {
            taskName: "並び替え",
            taskId: "522eb3f2-0a0b-4aee-bf0b-d9dae6a27dfb",
            isClose: false,
            isSelected: false,
            isFocus: true,
            checked: false,
            childTasks: [
              {
                taskName: "一定量ドラッグ",
                taskId: "09085be3-7930-4740-b7f0-dd0ff058786d",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [],
              },
            ],
          },
        ],
      },
      {
        taskName: "ショートカット",
        taskId: "0cb4c402-1307-4657-a524-03e5f8db5459",
        isClose: false,
        isSelected: false,
        isFocus: true,
        checked: false,
        childTasks: [
          {
            taskName: "グローバル",
            taskId: "fbc6cb7c-0689-48c0-b2c4-3e11c824186c",
            isClose: false,
            isSelected: false,
            isFocus: true,
            checked: false,
            childTasks: [
              {
                taskName: "undo/ redo",
                taskId: "ce3b631e-4641-4691-9bb5-a6abf799ac32",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [
                  {
                    taskName: "Ctrl+z/ Ctrl+Shift+z",
                    taskId: "057e27b9-fb05-4485-85a8-1514178f622c",
                    isClose: false,
                    isSelected: false,
                    isFocus: true,
                    checked: false,
                    childTasks: [],
                  },
                ],
              },
              {
                taskName: "ZoomIn/ ZoomOut",
                taskId: "b88ba03e-1f1f-4ea5-ac06-f08449d635a1",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [
                  {
                    taskName: "ctrl+MouseWheel",
                    taskId: "6731f7c6-764a-4387-ad96-3a227d8606af",
                    isClose: false,
                    isSelected: false,
                    isFocus: true,
                    checked: false,
                    childTasks: [],
                  },
                ],
              },
            ],
          },
          {
            taskName: "入力時",
            taskId: "23732c2d-c071-42ca-9f3b-f4e4ea721b11",
            isClose: false,
            isSelected: false,
            isFocus: true,
            checked: false,
            childTasks: [
              {
                taskName: "兄弟タスクの追加",
                taskId: "9cb18413-700c-4336-b1d3-05215138ac5b",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [
                  {
                    taskName: "Enter",
                    taskId: "0ce667f9-1a53-4dff-b0e6-b6fde4e4ed9a",
                    isClose: false,
                    isSelected: false,
                    isFocus: true,
                    checked: false,
                    childTasks: [],
                  },
                ],
              },
              {
                taskName: "子タスクの追加",
                taskId: "4266da20-3c8e-4f71-b8f3-01efa977212e",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [
                  {
                    taskName: "Tab",
                    taskId: "79f6f30e-9216-492b-84ca-9ff128cf6ae5",
                    isClose: false,
                    isSelected: false,
                    isFocus: true,
                    checked: false,
                    childTasks: [],
                  },
                ],
              },
              {
                taskName: "空タスクの削除",
                taskId: "d7007308-9ee6-472e-9b2e-9069eb846f12",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [
                  {
                    taskName: "Delete",
                    taskId: "99b66a78-dccb-4b0b-9b9e-367d0e0697a9",
                    isClose: false,
                    isSelected: false,
                    isFocus: true,
                    checked: false,
                    childTasks: [],
                  },
                ],
              },
            ],
          },
          {
            taskName: "ドラッグ中",
            taskId: "efbc4268-5712-4a58-99d1-12ec81bf2d36",
            isClose: false,
            isSelected: false,
            isFocus: true,
            checked: false,
            childTasks: [
              {
                taskName: "ドラッグの中断",
                taskId: "d8184d5c-4d81-46c4-82c3-7f0ecd75d01b",
                isClose: false,
                isSelected: false,
                isFocus: true,
                checked: false,
                childTasks: [
                  {
                    taskName: "Esc",
                    taskId: "75d6d9cf-0b2b-48a2-9105-587c3a949405",
                    isClose: false,
                    isSelected: false,
                    isFocus: true,
                    checked: false,
                    childTasks: [],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    centerPinTaskId: null,
    viewLevel: 0,
  },
];

export default initProjects;
